name: "LBM: CI Hooks"
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  deployment_status:
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
jobs:
  hooks:
    uses: henryre/lbm-poc/.github/workflows/_ci-hooks.yml@v1
    secrets: inherit
    with:
      config-path: lbm.toml
